### ISSUE TITLE
[Bug] Signora doesn't come out of her cocoon.

### ISSUE THREAD

**Issue by scooterboo** [Anime-Game-Servers/Grasscutter-Quests#158]
During the LaSignora battle, Signora doesn't come out of her cocoon.

I'm going to blame ModifyClimatePolygonParamTable being missing from Scriptlib:

```
06:07:35 <ERROR:SceneScriptManager> [LUA] call trigger failed in group 220114001 with action_EVENT_QUEST_FINISH_1046,org.anime_game_servers.gi_lua.models.ScriptArgs@1164198c
org.terasology.jnlua.LuaRuntimeException: null:340: attempt to call a nil value (field 'ModifyClimatePolygonParamTable')
	at org.terasology.jnlua.LuaState53.lua_pcall(Native Method)
	at org.terasology.jnlua.LuaState.call(LuaState.java:734)
	at org.terasology.jnlua.script.LuaScriptEngine.invokeFunction(LuaScriptEngine.java:181)
	at org.anime_game_servers.jnlua_engine.JNLuaScript.callMethod(JNLuaScript.java:121)
	at emu.grasscutter.scripts.SceneScriptManager.callScriptFunc(SceneScriptManager.java:827)
	at emu.grasscutter.scripts.SceneScriptManager.callTrigger(SceneScriptManager.java:778)
	at emu.grasscutter.scripts.SceneScriptManager.handleEventForTrigger(SceneScriptManager.java:742)
	at emu.grasscutter.scripts.SceneScriptManager.realCallEvent(SceneScriptManager.java:730)
	at emu.grasscutter.scripts.SceneScriptManager.lambda$callEvent$27(SceneScriptManager.java:718)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:264)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:840)
```
![image](https://github.com/user-attachments/assets/cc92a6f3-9111-4960-9783-836afbae05ae)

A few hits after:
![image](https://github.com/user-attachments/assets/91bcfffb-bc0b-4425-9c52-01c20abc418b)

There might be more issues after this one. This ticket will remain open until the LaSignora battle can be completed normally.

**Which branch did you use?**
refactoring_multiproto_0.2
Grasscutter version: 1.4.4-dev-48ebfc6f
Git Hash: 48ebfc6ff36ac2078388da0f5d9a74cbfbe72461 (it's local)

**Comment by scooterboo** [comment]
When Signora dies, a second call to ModifyClimatePolygonParamTable happens:

```
06:32:58 <ERROR:SceneScriptManager> [LUA] call trigger failed in group 220114001 with action_EVENT_ANY_MONSTER_DIE_1006,org.anime_game_servers.gi_lua.models.ScriptArgs@1511c3b4
org.terasology.jnlua.LuaRuntimeException: null:430: attempt to call a nil value (field 'ModifyClimatePolygonParamTable')
	at org.terasology.jnlua.LuaState53.lua_pcall(Native Method)
	at org.terasology.jnlua.LuaState.call(LuaState.java:734)
	at org.terasology.jnlua.script.LuaScriptEngine.invokeFunction(LuaScriptEngine.java:181)
	at org.anime_game_servers.jnlua_engine.JNLuaScript.callMethod(JNLuaScript.java:121)
	at emu.grasscutter.scripts.SceneScriptManager.callScriptFunc(SceneScriptManager.java:827)
	at emu.grasscutter.scripts.SceneScriptManager.callTrigger(SceneScriptManager.java:778)
	at emu.grasscutter.scripts.SceneScriptManager.handleEventForTrigger(SceneScriptManager.java:742)
	at emu.grasscutter.scripts.SceneScriptManager.realCallEvent(SceneScriptManager.java:730)
	at emu.grasscutter.scripts.SceneScriptManager.lambda$callEvent$27(SceneScriptManager.java:718)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:264)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:840)
```

**Comment by scooterboo** [comment]
You can make the cutscene happen with `/c 201901 then /spawn 29050102 cfg1004 grp220114001`, but Signora remains missing.

**Comment by scooterboo** [comment]
to play cutscene:
`/c 201901`
spawn second form of Signora:
`/spawn 29050102 cfg1004 grp220114001`
